[package]
name = "tusks-test"
version = "1.2.1"
edition = "2024"

[dependencies]
clap = { version = "4.5.50", features = ["string", "derive"] }
tusks = { path = "../tusks" }

[dev-dependencies]
assert_cmd = "2.1.1"
predicates = "3.1.3"
